/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F407x.h"

void delay(uint32_t count)
{
	for(uint32_t i = 0; i <= count; i++);
}


int main(void)
{

	LCD_init();
	LCDDisplayClear();
	delay(10000);
	while(1)
	{
		LCDPrintString("HD44780 LCD INTF");
		LCDSetCursor(2, 1);
		LCDPrintString("MOTOROLA 6800 SI");
		delay(1000000);
		LCDDisplayClear();
		LCDPrintString("STM32 + HD44780 ");
		LCDSetCursor(2, 1);
		LCDPrintString("LCD INTF PROJECT");
		delay(1000000);
		LCDDisplayClear();
	}

	while(1);
	return 0;
}
